- name: Create Gitea user
  user:
    comment: "Git Version control"
    create_home: False
    name: gitea
    shell: /usr/bin/false
    system: True

- name: Create Git config directory
  file:
    group: gitea
    owner: gitea
    path: /etc/gitea
    state: directory

- name: Create Gitea storage directories
  file:
    group: gitea
    mode: 0750
    owner: gitea
    path: /var/lib/gitea/{{ item }}
    state: directory
  loop:
    - "custom"
    - "data"
    - "log"

- name: Install Gitea
  get_url:
    dest: /usr/local/bin/gitea
    url: "{{ gitea.url}}/gitea-{{ gitea.release.current }}-linux-amd64"
    mode: 0750
    owner: gitea
    group: gitea

- name: Deploy Gitea systemd unit file
  copy:
    dest: /usr/lib/systemd/system/
    src: files/gitea.service
    mode: 0640

- name: Start Gitea
  systemd:
    enabled: True
    name: gitea
    state: started
