#############
#### SSH ####
#############
- name: Set SSH rules
  ufw:
    port: "{{ ufw.ssh.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.ssh.hosts}}"

###############
#### Vault ####
###############
- name: Set Vault rules
  ufw:
    comment: "Vault rules"
    port: "{{ ufw.vault.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.vault.hosts }}"

- name: Set Sabnzbd rules
  ufw:
    comment: "Sabnzbd rules"
    port: "{{ ufw.sabnzbd.secure_web.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.sabnzbd.hosts }}"

######################    
#### Transmission ####
######################
- name: Set Transmission web interface
  ufw:
    comment: "Transmission web interface"
    port: "{{ ufw.transmission.web.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.transmission.hosts }}"

- name: Set Transmission peer port
  ufw:
    port: "{{ ufw.transmission.peer.port }}"
    proto: "tcp"
    rule: "allow"
    comment: "Transmission peer port"

- name: Set Transmission peer port
  ufw:
    rule: "allow"
    port: "{{ ufw.transmission.peer.port }}"
    proto: "udp"
    comment: "Transmission peer port"

#################
#### Pihole #####
#################
## Everyone can use DNS
- name: Set Pihole DNS port
  ufw:
    comment: "Pihole DNS"
    port: "{{ ufw.pihole.dns.port }}"
    proto: "udp"
    rule: "allow"

- name: Set Pihole web interface port
  ufw:
    comment: "Pihole Web interface"
    port: "{{ ufw.pihole.web.port }}"
    proto: "tcp"
    src: "{{ item }}"
    rule: "allow"
  loop: "{{ ufw.pihole.hosts }}"

- name: Set the Pihole secure web port
  ufw:
    port: "{{ ufw.pihole.secure_web.port }}"
    proto: "tcp"
    src: "{{ item }}"
    rule: "allow"
    comment: "Pihole secure web interface"
  loop: "{{ ufw.pihole.hosts }}"

## Everyone gets DHCP
- name: Set Pihole DHCP port
  ufw:
    rule: "allow"
    port: "{{ ufw.pihole.dhcp.port }}"
    proto: "udp"
    comment: "Pihole DHCP"

##############
#### Plex ####
##############
- name: Set Plex port
  ufw:
    comment: "Plex Media Server Port"
    port: "{{ ufw.plex.main.port }}"
    proto: "tcp"
    rule: "allow"
  
- name: Set Plex DLNA ports
  ufw:
    comment: "Plex DLNA ports"
    port: "{{ item }}"
    proto: "udp"
    rule: "allow"
  loop: "{{ ufw.plex.dlna.ports }}"
    
- name: Set Plex GDM discovery ports
  ufw:
    comment: "Plex GDM ports"
    port: "{{ item }}"
    proto: "udp"
    rule: "allow"
  loop: "{{ ufw.plex.gdm.ports }}"

###################
#### Portainer ####
###################
- name: Set Portainer web port
  ufw:
    comment: "Portainer Web Port"
    port: "{{ ufw.portainer.web.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.portainer.hosts }}"
###############
#### Gitea ####
###############
- name: Set Gitea web port
  ufw:
    comment: "Gitea Web Port"
    port: "{{ ufw.gitea.web.port }}"
    proto: "tcp"
    rule: "allow"
    src: "{{ item }}"
  loop: "{{ ufw.gitea.hosts }}"

- name: Set UFW policy
  ufw:
    state: "{{ ufw.state }}"
    policy: "{{ ufw.policy }}"
