- hosts: docker
  gather_facts: yes
  become: yes
  vars:
    docker_disk: '/dev/sda'
    docker_disk_fs: 'xfs'
    docker_disk_path: '/var/lib/docker'
    docker_ubuntu_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    docker_ubuntu_ce_prereqs: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tasks:
    - name: Install docker-ce pre-reqs
      apt:
        name: '{{ docker_ubuntu_ce_prereqs }}'
        state: present
        update_cache: True

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add docker-ce repo
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        create: True
        mode: 0644
        line: '{{ docker_repo }}'
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: True

    - name: Format '{{ docker_disk }}' as '{{ docker_disk_fs }}'
      filesystem:
        dev: '{{ docker_disk }}'
        fstype: '{{ docker_disk_fs }}'
      ignore_errors: True

    - name: Mount '{{ docker_disk }}' under '{{ docker_disk_path }}'
      mount:
        path: '{{ docker_disk_path }}'
        src: '{{ docker_disk }}'
        state: mounted
        fstype: '{{ docker_disk_fs }}'
        opts: defaults
        dump: 0
        passno: 0 
      notify:
        - restart-docker

    - name: Start docker
      systemd:
        name: docker
        state: started
        enabled: True
  handlers:
    - name: Restat Docker daemon
      systemd:
        name: docker
        state: restarted
        enabled: True
      listen:
        - restart-docker 
