k8s_certs_system_config:
  # https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-admin-client-certificate
  - name: 'admin'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:masters'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
 # https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kubernetes-api-server-certificate
  - name: 'api_scheduler'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'Kubernetes'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-controller-manager-client-certificate
  - name: 'controller_manager'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:kube-controller-manager'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kube-proxy-client-certificate
  - name: 'kube_proxy'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:node-proxier'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-scheduler-client-certificate
  - name: 'kube_scheduler'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:kube-scheduler'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-service-account-key-pair
  - name: 'service_account'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'Kubernetes'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-admin-client-certificate
k8s_certs_kubelet_config:
  - name: 'worker-0'
    dns:
      - 'DNS:worker-0.example.com'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:nodes'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'

  - name: 'worker-1'
    dns:
      - 'DNS:worker-1.example.com'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:nodes'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'

  - name: 'worker-2'
    dns:
      - 'DNS:worker-2.example.com'
    country_name: 'US'
    key_size: 4096
    locality_name: 'Salt Lake City'
    organization_name: 'system:nodes'
    organizational_unit_name: 'Kubernetes The Hard Way'
    state_or_province_name: 'UT'

worker_hostnames:
  - 'worker-0'
  - 'worker-1'
  - 'worker-2'
fqdns:
  - 'worker-0.example.com'
  - 'worker-1.example.com'
  - 'worker-2.example.com'
