#cloud-config
users:
  - name: exnihlio
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE9PQicXfyqM+FHW6aI00eMu3Y3m0pGCQp2eed2FEtzO"
networks:
  ethernets:
    enp0s1:
      match:
        name: "enp0s1"
      addresses:
        - 192.168.205.
