- name: Validate Nginx Config
  shell: docker exec {{ repo.container }} nginx -t
  listen:
    - validate-nginx-conf

- name: Restart Nginx
  shell: docker exec {{ repo.container }} nginx -s reload
  listen:
    - restart-nginx
