## Vault directories
- name: Create Vault storage directories
  file:
    state: directory
    path: "{{ item.value }}" 
    owner: root
    group: root
    mode: 0750
  loop: "{{ vault.dirs | dict2items }}"
  become: True

- name: Render the vault-server.hcl template 
  template:
    src: templates/vault-server.template
    dest: "{{ vault.dirs.config }}/vault-server.hcl"
  become: True

- name: Render Dockerfile template
  template:
    src: templates/docker-compose.template
    dest: ./docker-compose.yml

- name: Deploy the containers
  docker_compose:
    project_src: .
    state: present
