- name: Create registry storage directory
  file:
    path: /data/disks/registry/storage
    state: directory

- name: Create the registry auth directory
  file:
    group: root
    owner: root
    mode: 0700
    path: /data/disks/registry/auth
    state: directory

- name: Create the Portainer storage directory
  file:
    group: root
    path: /data/disks/config/portainer/storage
    mode: 0700
    owner: root
    state: directory

- name: Copy the registry auth file
  copy:
    decrypt: True
    dest: /data/disks/registry/auth/
    group: root
    owner: root
    mode: 0600
    src: files/htpasswd

- name: Copy the nginx conf file
  copy:
    dest: /data/disks/nginx/conf/
    owner: root
    group: root
    mode: 0600
    src: templates/nginx.j2
  notify:
    - validate-nginx-conf
    - restart-nginx

- name: Render Dockerfile template
  template:
    src: templates/docker-compose.j2
    dest: ./docker-compose.yml

- name: Deploy the containers
  docker_compose:
    project_src: .
    state: present
