- name: Create registry storage directory
  file:
    path: /data/disks/registry/storage
    state: directory

- name: Render Dockerfile template
  template:
    src: templates/docker-compose.template
    dest: ./docker-compose.yml

- name: Deploy the containers
  docker_compose:
    project_src: .
    state: present
