- name: Create registry storage directory
  file:
    group: root
    mode: 0700
    owner: root
    path: /data/disks/registry/storage
    state: directory

- name: Create the registry auth directory
  file:
    group: root
    owner: root
    mode: 0700
    path: /data/disks/registry/auth
    state: directory

- name: Create the Portainer storage directory
  file:
    group: root
    path: /data/disks/config/portainer/storage
    mode: 0700
    owner: root
    state: directory

- name: Copy the registry auth file
  copy:
    decrypt: true
    dest: /data/disks/registry/auth/
    group: root
    owner: root
    mode: 0600
    src: files/htpasswd

- name: Copy the nginx conf file
  template:
    dest: /data/disks/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: 0600
    src: templates/nginx.j2
  notify:
    - validate-nginx-conf
    - restart-nginx
## Start moving from Docker compose to standalone containers
- name: Start Drone Server
  docker_container:
    detach: true
    dns_servers:
      - "10.1.10.20"
    domainname: "{{ cicd.domainname }}"
    etc_hosts:
      git.sami.dog: "10.1.10.20"
    env: "{{ cicd.server.env }}"
    hostname: "{{ cicd.hostname }}"
    image: "{{ cicd.image }}:{{ cicd.tag }}"
    mounts:
      - source: "{{ certpath }}"
        target: /certs
        type: bind
        read_only: true
      - source: drone-db
        target: /data
        type: volume
      - source: /var/run/docker.sock
        target: /var/run/docker.dock
        type: bind
    name: "services_drone_server"
    network_mode: "bridge"
    ports:
      - "10443:443"
    restart_policy: "unless-stopped"
    state: "started"

- name: Deploy Drone Runner
  docker_container:
    detach: true
    dns_servers:
      - "10.1.10.20"
    domainname: "{{ cicd.domainname }}"
    etc_hosts:
      cicd.sami.dog: "10.1.10.20"
      git.sami.dog: "10.1.10.20"
    env: "{{ cicd.runner.env }}"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    name: "services_drone_runner"
    network_mode: "bridge"
    restart_policy: "unless-stopped"
    state: "started"

- name: Render Dockerfile template
  template:
    group: root
    mode: 0644
    owner: root
    src: templates/docker-compose.j2
    dest: ./docker-compose.yml

- name: Deploy the containers
  docker_compose:
    project_src: .
    state: present
